type: yolov8
name: yolov8t-r20230811
display_name: YOLOv8t Ultralytics
model_path: https://raw.githubusercontent.com/JsutCheng/Popuponnx/main/yolov8n.onnx
input_width: 640
input_height: 640
score_threshold: 0.5
nms_threshold: 0.45
confidence_threshold: 0.45
classes:
  - close
  - popup
